homeroom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('classrooms/', views.classroom_index, name='classrooms_index'),
    path('classrooms/<int:classroom_id>/',
         views.classrooms_detail, name='classroom_detail'),
    path('classrooms/create/', views.ClassroomCreate.as_view(),
         name='classrooms_create'),
    path('classrooms/<int:pk>/update/',
         views.ClassroomUpdate.as_view(), name='classrooms_update'),
    path('classrooms/<int:pk>/delete/',
         views.ClassroomDelete.as_view(), name='classrooms_delete'),
    path('classrooms/<int:pk>/create_assignment/', 
          views.AssignmentCreate.as_view(), name='assignment_create'),
    path('assignments/', views.AssignmentList.as_view(), name='assignments_index'), 
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime, date
from django.utils import timezone

from django.contrib.auth.models import User

USER_TYPES = (
    ('admin', 'Admin'),
    ('teacher', 'Teacher'),
    ('student', 'Student')
)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(
        max_length=10,
        choices=USER_TYPES,
        default='student'
    )
    address = models.CharField(max_length=200)
    phone_number = models.IntegerField()

    def __str__(self):
        return f" Username: {self.user} | Usertype: {self.get_user_type_display()}"


class Classroom(models.Model):
    subject = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(
        max_length=500, default='Enter A Description')

    def __str__(self):
        return f" Username: {self.user} | Subject: {self.subject}"

    def get_absolute_url(self):
        return reverse('classroom_detail', kwargs={'classroom_id': self.id})


class Assignment(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    grade = models.IntegerField(default=0)
    date_created = models.DateField(default=timezone.now)
    due_date = models.DateField('due date')
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)

    def __str__(self):
        return f" Subject: {self.classroom.subject} | Assignment: {self.name}"

    def get_absolute_url(self):
        return reverse('classroom_detail', kwargs={'classroom_id': self.classroom.id})


class AutoDateTimeField(models.DateTimeField):
    def pre_save(self, model_instance, add):
        return timezone.now()

main_app/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Classroom, Assignment


class ExtendedUserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=200)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name',
                  'last_name', 'password1', 'password2')


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('user_type', 'address', 'phone_number')


class ClassForm(ModelForm):
    class Meta:
        model = Classroom
        fields = ['subject', 'user']


class AssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ['name', 'description', 'grade', 'due_date']

main_app/views.py
import logging
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect

from .models import Classroom, Assignment
from .forms import ProfileForm, ExtendedUserForm

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


from django.http import HttpResponse

logger = logging.getLogger(__name__)


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


@login_required
def classroom_index(request):
    classrooms = Classroom.objects.all()
    return render(request, 'classroom/classroom-list.html', {'classrooms': classrooms})


@login_required
def classrooms_detail(request, classroom_id):
    classroom = Classroom.objects.get(id=classroom_id)
    assignment = Assignment.objects.all()
    return render(request, 'classroom/classroom-detail.html', {
        'classroom': classroom, 'assignment': assignment
    })


def signup(request):
    if request.method == 'POST':
        form = ExtendedUserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            login(request, user)
            return redirect('home')
        else:
            return render(request, 'registration/signup.html', {'form': form, 'profile_form': profile_form})
    form = ExtendedUserForm()
    profile_form = ProfileForm()
    context = {'form': form, 'profile_form': profile_form}
    return render(request, 'registration/signup.html', context)


class ClassroomCreate(LoginRequiredMixin, CreateView):
    model = Classroom
    fields = ['subject', 'description']
    success_url = '/classrooms/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ClassroomUpdate(LoginRequiredMixin, UpdateView):
    model = Classroom
    fields = ['subject', 'description']


class ClassroomDelete(LoginRequiredMixin, DeleteView):
    model = Classroom
    success_url = '/classrooms/'


class AssignmentCreate(LoginRequiredMixin, CreateView):
    model = Assignment
    fields = ['name', 'description', 'grade', 'due_date']

    def form_valid(self, form):
        form.instance.classroom_id = self.kwargs.get('pk')
        return super(AssignmentCreate, self).form_valid(form)


class AssignmentUpdate(LoginRequiredMixin, UpdateView):
    model = Assignment
    fields = ['name', 'description', 'grade', 'due_date']
    success_url = '/assigments/'


class AssignmentDelete(LoginRequiredMixin, DeleteView):
    model = Assignment
    success_url = '/assigments/'


class AssignmentList(LoginRequiredMixin, ListView):
    model = Assignment


class AssignmentDetail(LoginRequiredMixin, DetailView):
    model = Assignment

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

{% load static %}

<h1 style="margin-left: 100px;">About HomeRoom</h1>
<div>
<img src="{% static 'images/classroom-clipart.png' %}"  style="border-radius: 10px; margin:13px 7px -4px 200px; border: 10px; border-style: outset;"width="40%" height="40%">
</div>

<hr />
<div class="container" style="border-radius: 10px; background-color: #86dcfc96;">
<p style="margin:10px;  font-size: 25px; font-family: 'Nanum Pen Script', cursive;">
    Our mission is to make education accessible and empowering for students and teachers.
We’ve made it our goal to provide an online classroom with a user friendly experience for students and teachers, enabling assignments to be distributed, managed and updated effectively and  efficiently. 
The world is faced with a need for reliable and user-friendly educational software. Students aren’t able to sit face to face with teachers and teachers are forced implement lesson plans from afar. 
</div>

</p>
{% endblock %}

main_app/templates/assignments/assignment-confirm-delete.html
{% extends 'base.html' %}

{% block content %}

<!-- Page should only be seen if user is a teacher
    Delete should delete assignment from class assignment list
    Cancel should link back to assignment-list.html  -->

<h1>Delete Assignment</h1>

<h4>Are you sure you want to delete?</h4>

<form>
    <input type="submit" value="Yes - Delete" class="btn red">
    <a class="btn blue">Cancel</a>
</form>

{% endblock %}

main_app/templates/assignments/assignment-detail.html
{% extends 'base.html' %}

{% block content %}

<!-- If user is teacher -->
<div class="card-content">    
    <div class="card-action">
    <a href="">Edit</a>
    <a href="">Delete</a>
    </div>
</div>
<!-- If user is student -->
<div class="card-content">    
<h3>Assignment Name</h3>
<form>
</form>
<input type="submit" value="submit">
</div>

{% endblock %}

main_app/templates/assignments/assignment-form.html
{% extends 'base.html' %}

{% block content %}

<!-- Should only be seen is user is a Teacher -->

<h1>Add Assignment</h1>

<div class="card-action">
    <form action="{% url 'assoc_assignment' class.id assignment.id %}" method="post">
        {% csrf_token %}
      <button type="submit" class="btn">Add</button>
    </form>
  </div>

{% endblock %}

main_app/templates/assignments/assignment-list.html
{% extends 'base.html' %}
{% block content %}

<!-- If no assignments  -->
<h3>There are no assignments at this time</h3>

<!-- If user is teacher 
    class name, list of students-->
<div class="card">
    <a>Class Name</a>
        <div class="card-content">
        </div>
    </a>
</div>
<!-- If user is student
    class name, list of assignments -->
    <div class="card">
        <a>Class Name</a>
            <div class="card-content">
            </div>
        </a>
    </div>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HomeRoom</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Nanum+Pen+Script&family=Permanent+Marker&display=swap" rel="stylesheet">    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo"><img src="{% static 'images/HomeRoomLogo2.png' %}"
                                width="100" height="100"></a></li>
                </ul>
                <ul class="right">
                    <li><a href="/about">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'classrooms_index' %}">View All Classrooms</a></li>
                    <li><a href="{% url 'classrooms_create' %}">Create a Class</a></li>
                    <li><a href="/"></a></li>
                    <li><a href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Log In</a></li>

                    
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserved, &copy; 2020 HomeRoom &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/classes/class_form.html
{% extends 'base.html' %}

{% block content %}

<!-- Should only be seen is user is Admin -->

<h1>Add Class</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" class="btn blue">
    <a class="btn red" href="{% url 'classrooms_index' %}">Cancel</a>
</form>


{% endblock %}

main_app/templates/classroom/classroom-detail.html
{% extends 'base.html' %}

{% block content %}

<!-- If user is admin -->

<div class="card" style="border-radius: 20px; margin: 100px;">
    <div class="card-content">
        <span class="card-title">{{ classroom.subject }}</span>
        <p>Description: {{ classroom.description }}</p>
        <table class="striped">
            <thead>
              <tr><th>Assignment</th><th>Description</th></tr>
            </thead>
            <tbody>
              {% for assignment in classroom.assignment_set.all %}
                <tr>
                  <td>{{assignment.name}}</td>
                  <td>{{assignment.description}}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        <!-- still need list of students here  -->
    </div>
<div class="card-action" style="border-radius: 0px 0px 10px 10px; background-color: #468AF6"">
    <a href="{% url 'classrooms_update' classroom.id %}" style="color: #fecc4d;">Edit</a>
    <a href="{% url 'classrooms_delete' classroom.id %}" style="color: #DA251D;">Delete</a>
    <a href="{% url 'assignment_create' classroom.id %}">Create Assignment</a>
</div>
   <!-- Available toys will come after this line -->
   <!-- </div> -->
<!-- <div class="card-action">
    <a href="">Edit</a>
    <a href="">Delete</a>
</div> -->

<!-- If user is teacher -->


{% endblock %}

main_app/templates/classroom/classroom-list.html
{% extends 'base.html' %}
{% block content %}

<h3>Dashboard</h3>
<!-- If user is admin
    class name, teacher name, list of students-->
{% if profile.user_type == admin and object_list.count == 0 %}
    <h3 class="red-text">There are no Classes</h3>
{% elif profile.user_type == admin %}
<div  class="row">
    {% for classroom in classrooms %}
    <div class="col s4">
    <div id="classcards" class="card">
        <a href="{% url 'classroom_detail' classroom.id %}">
            <div  class="card-content">
                <span class="card-title">{{ classroom.subject }}</span>
                <p>Description: {{ classroom.description }}</p>
                <!-- still need to add list of students here -->
            </div>
        </a>
    </div>
</div>

    {% endfor %}
</div>
<!-- If user is teacher 
    class name, list of students-->
{% elif profile.user_type == teacher and object_list.count == 0 %}
    <h3 class="red-text">There are no Classes</h3>
{% elif profile.user_type == teacher %}
    {% for classroom in classrooms %}
    <div  class="card">
        <a href="{% url 'classroom_detail' classroom.id %}">
            <div class="card-content">
                <span class="card-title">{{ classroom.subject }}</span>
                <!-- still need to add list of students here -->
            </div>
        </a>
    </div>
    {% endfor %}
<!-- If user is student
    class name, list of assignments -->
{% elif profile.user_type == student and object_list.count == 0 %}
    <h3 class="red-text">There are no Classes</h3>
{% elif profile.user_type == student %}
    {% for classroom in classrooms %}
    <div class="card">
        <a href="{% url 'classroom_detail' classroom.id %}">
            <div class="card-content">
                <span class="card-title">{{ classroom.subject }}</span>
                <!-- still need to add list of assignments here -->
            </div>
        </a>
    </div>
    {% endfor %}
{% endif %}
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<div class="">
<img src="{% static 'images/HomeRoomLogocrop.png' %}"  style="margin:80px 10px -40px 100px;"width="60%" height="60%">
</div>
    <div style="margin:10px;">
       <h4 class="" style="display: initial;
       margin-block-start: 0em;
       margin-block-end: 16.33em;
       margin-inline-start: 70px;
       margin-inline-end: 0px;
       line-height: 10px;
       font-size: 2.92rem;
       margin: 78px 4px -68px 57p;
       letter-spacing: -1px;
       color: #535353;
       font-family: 'Nanum Pen Script', cursive;
   ">"Where assignments are made easy"</h4> 
    </div>
            {% if user.is_authenticated %}
        <ul> 
        <div id="classpgbtn" class="class" style=" margin: 0px 10px 40px 90px;  display:flex; flex-wrap: no-wrap;" >
            <li id="classpgbtn"><a href="{% url 'classrooms_index' %}" class="btn blue" style="border-radius: 10px; margin-left: 40px; margin-right: 40px;">View All Classrooms</a></li>
            <li id="classpgbtn"><a href="{% url 'classrooms_create' %}" class="btn blue" style="border-radius: 10px;">Create a Class</a></li>
            
        </div>
        </ul>   
             {% else %}   
             <ul> 
                <div id="signpgbtn" class="class" style=" margin: 0px 10px 40px 90px; display:flex; flex-wrap: no-wrap;"" >
                    <li id="signpgbtn"><a href="{% url 'signup' %}" class="btn blue" style="border-radius: 10px; padding: 0px 40px 0px 40px;margin-left: 100px; margin-right: 40px;">Signup</a></li>
                    <li id="signpgbtn"><a href="{% url 'login' %}" class="btn blue" style="border-radius: 10px;padding: 0px 40px 0px 40px;">Login</a></li>
                    
                </div>
                </ul>   
   {% endif %}



{% endblock %}

main_app/templates/main_app/assignment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<!-- Page should only be seen if user is a teacher
    Delete should delete assignment from class assignment list
    Cancel should link back to assignment-list.html  -->

<h1>Delete Assignment</h1>

<h4>Are you sure you want to delete?</h4>

<form>
    <input type="submit" value="Yes - Delete" class="btn red">
    <a class="btn blue">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/assignment_form.html
{% extends 'base.html' %}

{% block content %}

<!-- Should only be seen is user is a Teacher -->
<h3 style="color: #3096f3; margin: 10px 170px;">Add Assignment</h3>
<div class="column" input="s2 col" style=" padding: 0 10px; border: 6px solid #3096f3; background-color: #86dcfc96;">
  <div class="card-action">
    <form method="post">
      {% csrf_token %}
      <table>
          {{ form.as_table }}
      </table>
      <button type="submit" class="btn blue" style="border-radius: 50px;border: none;
      padding: 0 16px;
      text-transform: uppercase;
      vertical-align: middle;
      margin: 10px 160px 10px">Add</button>
    </form>
  </div>
</div>

<script>
  var dateEl = document.getElementById('id_due_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

main_app/templates/main_app/classroom_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<!-- Page should only be seen if user is an admin
    Delete should delete class from class list
    Cancel should link back to class-list.html  -->

<div id="deletecontain" class= "container" style="border-radius: 10px; background-color: #fecc4db0; margin: 100px">
<h3 style="writing-mode: vertical-rl; background-color: #4087F7; border-radius: 10px 0 0px 10px; margin: 0; color:#FECC4D; padding: 1rem;" >Delete?</h3>

<h4 style="color:#808080; padding:30px; margin-block: 1em 2em;">Are you sure you want to delete <span class="blue-text">{{ object.subject }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn red" style="border-radius: 10px; color:rgb(230, 227, 222); margin:50px 0 0 0;">
    <a href="{% url 'classroom_detail' classroom.id %}" style="font-size: 18px; margin:  0 10px 0 10px; color:#808080">Cancel</a>
</form>
</div>

{% endblock %}

main_app/templates/main_app/classroom_form.html
{% extends 'base.html' %}

{% block content %}

<!-- Should only be seen is user is Admin -->

<h2 style="color: #3096f3; margin: 10px 230px;">Add Class</h2>
<div class="column" input="s2 col" style=" padding: 0 10px; border: 6px solid #3096f3; background-color: #86dcfc96;">

<form id="classform" action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input id="cf_button" type="submit" value="Submit" class="btn blue" style="border-radius: 50px;border: none;
    padding: 0 16px;
    text-transform: uppercase;
    vertical-align: middle;
    margin: 10px 160px 10px">
    <a  id="cf_cancel_button" class="btn" href="{% url 'classrooms_index' %}" style="border-radius: 50px;border: none;
    padding: 0 16px;
    text-transform: uppercase;
    vertical-align: middle;
    margin: 10px 160px 10px;
    background-color:#fecc4d; ;">Cancel</a>
</form>
</div>


{% endblock %}